
[HELPER]
	internal = "helper"
	shortcut = "seriex.helper"
	permissions = ["seriex.example_permission10", "seriex.example_permission9", "seriex.example_permission8", "seriex.example_permission7", "seriex.example_permission6", "seriex.example_permission5", "seriex.example_permission4", "seriex.example_permission3", "seriex.example_permission2", "seriex.example_permission1"]
	coolName = "&7[&dHelper&7]"

[ADMIN]
	internal = "admin"
	shortcut = "seriex.admin"
	permissions = ["seriex.example_permission10", "seriex.example_permission9", "seriex.example_permission8", "seriex.example_permission7", "seriex.example_permission6", "seriex.example_permission5", "seriex.example_permission4", "seriex.example_permission3", "seriex.example_permission2", "seriex.example_permission1"]
	coolName = "&7[&cAdmin&7]"

